#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v3
# autospec commit: 750e50d
#
# Source0 file verified with key 0x0FDE7BE0E88F5E48 (contact@emersion.fr)
#
Name     : xdg-desktop-portal-wlr
Version  : 0.7.0
Release  : 2
URL      : https://github.com/emersion/xdg-desktop-portal-wlr/releases/download/v0.7.0/xdg-desktop-portal-wlr-0.7.0.tar.gz
Source0  : https://github.com/emersion/xdg-desktop-portal-wlr/releases/download/v0.7.0/xdg-desktop-portal-wlr-0.7.0.tar.gz
Source1  : https://github.com/emersion/xdg-desktop-portal-wlr/releases/download/v0.7.0/xdg-desktop-portal-wlr-0.7.0.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xdg-desktop-portal-wlr-data = %{version}-%{release}
Requires: xdg-desktop-portal-wlr-libexec = %{version}-%{release}
Requires: xdg-desktop-portal-wlr-license = %{version}-%{release}
Requires: xdg-desktop-portal-wlr-man = %{version}-%{release}
Requires: xdg-desktop-portal-wlr-services = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(inih)
BuildRequires : pkgconfig(libpipewire-0.3)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(scdoc)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-protocols)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# xdg-desktop-portal-wlr
[![builds.sr.ht status](https://builds.sr.ht/~emersion/xdg-desktop-portal-wlr/commits/master.svg)](https://builds.sr.ht/~emersion/xdg-desktop-portal-wlr/commits/master?)

%package data
Summary: data components for the xdg-desktop-portal-wlr package.
Group: Data

%description data
data components for the xdg-desktop-portal-wlr package.


%package libexec
Summary: libexec components for the xdg-desktop-portal-wlr package.
Group: Default
Requires: xdg-desktop-portal-wlr-license = %{version}-%{release}

%description libexec
libexec components for the xdg-desktop-portal-wlr package.


%package license
Summary: license components for the xdg-desktop-portal-wlr package.
Group: Default

%description license
license components for the xdg-desktop-portal-wlr package.


%package man
Summary: man components for the xdg-desktop-portal-wlr package.
Group: Default

%description man
man components for the xdg-desktop-portal-wlr package.


%package services
Summary: services components for the xdg-desktop-portal-wlr package.
Group: Systemd services
Requires: systemd

%description services
services components for the xdg-desktop-portal-wlr package.


%prep
%setup -q -n xdg-desktop-portal-wlr-0.7.0
cd %{_builddir}/xdg-desktop-portal-wlr-0.7.0
pushd ..
cp -a xdg-desktop-portal-wlr-0.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707108520
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
mkdir -p %{buildroot}/usr/share/package-licenses/xdg-desktop-portal-wlr
cp %{_builddir}/xdg-desktop-portal-wlr-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/xdg-desktop-portal-wlr/116d5a36c887b5dd6a318a25562f67e206efab29 || :
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/services/org.freedesktop.impl.portal.desktop.wlr.service
/usr/share/xdg-desktop-portal/portals/wlr.portal

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/xdg-desktop-portal-wlr
/usr/libexec/xdg-desktop-portal-wlr

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xdg-desktop-portal-wlr/116d5a36c887b5dd6a318a25562f67e206efab29

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/xdg-desktop-portal-wlr.5

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/user/xdg-desktop-portal-wlr.service
